<?php

return [
    'APP_ENV' => env('APP_ENV')
    , 'VUE_APP_CIDADE_NOME' => env('VUE_APP_CIDADE_NOME')
    , 'VUE_APP_CIDADE_ID' => env('VUE_APP_CIDADE_ID')
    , 'VUE_APP_CIDADE_IBGE' => env('VUE_APP_CIDADE_IBGE')
    , 'VUE_APP_CIDADECEP' => env('VUE_APP_CIDADECEP')
];


/*
APP_CIDADE_NOME="SÃO MATEUS DO MARANHÃO"
APP_CIDADE_ID="1571"
APP_CIDADE_IBGE="2111508"
APP_CIDADE_CEP="65.470-000"
 */